/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import static Backend.Validations.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Meganl
 */
public class Signup extends javax.swing.JFrame 
{

    /**
     * Creates new form GUI
     */
    public Signup() 
    {
        initComponents();
        
        //variables for the years offered for the birthday
        int lowestYearAvailable = 1903;
        int highestYearAvailable = 2005;
        
        
        //sets all the error messages to not be visible
        noNameErrorMessage.setVisible(false);
        badPasswordErrorMessage.setVisible(false);
        noExistingDateErrorMessage.setVisible(false);
        noOptionSelectedErrorMessage.setVisible(false);
        unappropriateAgeErrorMessage.setVisible(false);
        birthdateAndAgeDontCoicideErrorMessage.setVisible(false);
        
        
        //setting the values for the date
        //year
        ArrayList<String> yearList = new ArrayList<>();
        for(int i = lowestYearAvailable; i < highestYearAvailable + 1; i++)
        {
            yearList.add(i + "");
        }
        DefaultComboBoxModel yearComboModel = new DefaultComboBoxModel(yearList.toArray());
        yearComboBox.setModel(yearComboModel);
        //month
        ArrayList<String> monthList = new ArrayList<>();
        monthList.add("January");
        monthList.add("February");
        monthList.add("March");
        monthList.add("April");
        monthList.add("May");
        monthList.add("June");
        monthList.add("July");
        monthList.add("August");
        monthList.add("September");
        monthList.add("October");
        monthList.add("November");
        monthList.add("December");
        DefaultComboBoxModel monthComboModel = new DefaultComboBoxModel(monthList.toArray());
        monthComboBox.setModel(monthComboModel);
        //day
        ArrayList<String> dayList = new ArrayList<>();
        for(int i = 1; i < 32; i++)
        {
            dayList.add(i + "");
        }
         DefaultComboBoxModel dayComboModel = new DefaultComboBoxModel(dayList.toArray());
        dayComboBox.setModel(dayComboModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        yesOption = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        yearComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        noOption = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        noNameErrorMessage = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        badPasswordErrorMessage = new javax.swing.JLabel();
        noExistingDateErrorMessage = new javax.swing.JLabel();
        noOptionSelectedErrorMessage = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        unappropriateAgeErrorMessage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        birthdateAndAgeDontCoicideErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("VeryGreatUniversity.org Signup");

        jLabel2.setText("What is your age? Type it in number form.");

        jLabel3.setText("Is this you first year here?");

        jLabel4.setText("What's your name?");

        jLabel5.setText("When were you born?");

        nameField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nameFieldActionPerformed(evt);
            }
        });

        yesOption.setText("Yes");
        yesOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yesOptionActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                submitButtonActionPerformed(evt);
            }
        });

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Year:");

        jLabel7.setText("Month: ");

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Day:");

        noOption.setText("No");

        jLabel9.setText("Insert your password. It must be 8 characters in length, contain ");

        noNameErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        noNameErrorMessage.setText("**PLEASE ENTER YOUR NAME**");

        passwordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("a number, and contain both upper case and lower case letters");

        badPasswordErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        badPasswordErrorMessage.setText("**PLEASE ADHERE TO THE REQUIREMENTS**");

        noExistingDateErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        noExistingDateErrorMessage.setText("**PLEASE SELECT AN EXISTING DATE**");

        noOptionSelectedErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        noOptionSelectedErrorMessage.setText("**PLEASE SELECT A SINGULAR OPTION**");

        unappropriateAgeErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        unappropriateAgeErrorMessage.setText("**PLEASE SELECT AN APPROPRIATE AGE AS A DIGIT**");

        jLabel11.setText("Please note that you need to be 18+  this year to be a part of this community.");

        birthdateAndAgeDontCoicideErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        birthdateAndAgeDontCoicideErrorMessage.setText("**YOUR BIRTHDATE AND AGE DO NOT MATCH**");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noOptionSelectedErrorMessage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yesOption)
                                .addGap(36, 36, 36)
                                .addComponent(noOption)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noNameErrorMessage))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearComboBox, 0, 94, Short.MAX_VALUE)
                                    .addComponent(monthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dayComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noExistingDateErrorMessage)
                                    .addComponent(birthdateAndAgeDontCoicideErrorMessage)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(badPasswordErrorMessage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unappropriateAgeErrorMessage))
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noNameErrorMessage))
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badPasswordErrorMessage))
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(noExistingDateErrorMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthdateAndAgeDontCoicideErrorMessage))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unappropriateAgeErrorMessage))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(noOptionSelectedErrorMessage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yesOption)
                            .addComponent(noOption))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void yesOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesOptionActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitButtonActionPerformed
    {//GEN-HEADEREND:event_submitButtonActionPerformed
        //checking if there is input in the name field
        if(isNameFieldNull(nameField.getText()))
        {
            noNameErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            noNameErrorMessage.setVisible(false);
        }
        
        
        //checking if the password is valid
        if(!isPasswordValid(passwordField.getText()))
        {
            badPasswordErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            badPasswordErrorMessage.setVisible(false);
        }
        
        
        //checks to see if the date was valid
        if(!isDateReal(dayComboBox.getItemAt(dayComboBox.getSelectedIndex()), monthComboBox.getItemAt(monthComboBox.getSelectedIndex()), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())))
        {
            noExistingDateErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            noExistingDateErrorMessage.setVisible(false);
        }
        
        
        //checks to see if the age meets the requirements
        if(!isAgeWithinRange(ageField.getText()))
        {
            unappropriateAgeErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            unappropriateAgeErrorMessage.setVisible(false);
        }
        
        
        //checks to see if the age and birthdate coincide
        if(!isBirthdayAndAgeRelated(ageField.getText(), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())))
        {
            birthdateAndAgeDontCoicideErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            birthdateAndAgeDontCoicideErrorMessage.setVisible(false);
        }
        
        
        //checking if an option was chosen
        if(isNoOrTwoOptionsChosen(yesOption.isSelected(), noOption.isSelected()))
        {
            noOptionSelectedErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            noOptionSelectedErrorMessage.setVisible(false);
        }
        
        
        //if everything entered is correct then the user is redirected to the welcome message
        if(!isNameFieldNull(nameField.getText()) && isPasswordValid(passwordField.getText()) && isDateReal(dayComboBox.getItemAt(dayComboBox.getSelectedIndex()), monthComboBox.getItemAt(monthComboBox.getSelectedIndex()), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())) && isAgeWithinRange(ageField.getText()) && isBirthdayAndAgeRelated(ageField.getText(), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())) && !isNoOrTwoOptionsChosen(yesOption.isSelected(), noOption.isSelected()))
        {
            new SignupComplete().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordFieldActionPerformed
    {//GEN-HEADEREND:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel badPasswordErrorMessage;
    private javax.swing.JLabel birthdateAndAgeDontCoicideErrorMessage;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel noExistingDateErrorMessage;
    private javax.swing.JLabel noNameErrorMessage;
    private javax.swing.JCheckBox noOption;
    private javax.swing.JLabel noOptionSelectedErrorMessage;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel unappropriateAgeErrorMessage;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JCheckBox yesOption;
    // End of variables declaration//GEN-END:variables
}
