/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import static Backend.Validations.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Meganl
 */
public class Signup extends javax.swing.JFrame 
{

    /**
     * Creates new form GUI
     */
    public Signup() 
    {
        initComponents();
        
        //variables for the years offered for the birthday
        int lowestYearAvailable = 1903;
        int highestYearAvailable = 2005;
        
        
        //sets all the error messages to not be visible
        noNameErrorMessage.setVisible(false);
        badPasswordErrorMessage.setVisible(false);
        noExistingDateErrorMessage.setVisible(false);
        noOptionSelectedErrorMessage.setVisible(false);
        unappropriateAgeErrorMessage.setVisible(false);
        birthdateAndAgeDontCoicideErrorMessage.setVisible(false);
        
        
        //setting the values for the date
        //year
        ArrayList<String> yearList = new ArrayList<>();
        for(int i = lowestYearAvailable; i < highestYearAvailable + 1; i++)
        {
            yearList.add(i + "");
        }
        DefaultComboBoxModel yearComboModel = new DefaultComboBoxModel(yearList.toArray());
        yearComboBox.setModel(yearComboModel);
        //month
        ArrayList<String> monthList = new ArrayList<>();
        monthList.add("January");
        monthList.add("February");
        monthList.add("March");
        monthList.add("April");
        monthList.add("May");
        monthList.add("June");
        monthList.add("July");
        monthList.add("August");
        monthList.add("September");
        monthList.add("October");
        monthList.add("November");
        monthList.add("December");
        DefaultComboBoxModel monthComboModel = new DefaultComboBoxModel(monthList.toArray());
        monthComboBox.setModel(monthComboModel);
        //day
        ArrayList<String> dayList = new ArrayList<>();
        dayList.add("01");
        dayList.add("02");
        dayList.add("03");
        dayList.add("04");
        dayList.add("05");
        dayList.add("06");
        dayList.add("07");
        dayList.add("08");
        dayList.add("09");
        for(int i = 10; i < 32; i++)
        {
            dayList.add(i + "");
        }
         DefaultComboBoxModel dayComboModel = new DefaultComboBoxModel(dayList.toArray());
        dayComboBox.setModel(dayComboModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        yesOption = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        yearComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        noOption = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        noNameErrorMessage = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        badPasswordErrorMessage = new javax.swing.JLabel();
        noExistingDateErrorMessage = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        unappropriateAgeErrorMessage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        birthdateAndAgeDontCoicideErrorMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        noOptionSelectedErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VeryGreatUniversity.org Signup");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 12, -1, 41));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("What is your age? Type it in number form.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 359, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Is this you first year here?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 439, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("When were you born?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, -1, -1));

        usernameField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 101, -1));

        yesOption.setText("Yes");
        yesOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yesOptionActionPerformed(evt);
            }
        });
        getContentPane().add(yesOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 456, -1, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 474, -1, -1));

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 229, 94, 32));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Year:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 238, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Month: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, -1, -1));

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(dayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 305, 94, 35));

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(monthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 267, 94, 32));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Day:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 315, -1, -1));

        noOption.setText("No");
        getContentPane().add(noOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 456, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Insert your password. It must be 8 characters in length, contain ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 125, -1, -1));

        noNameErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        noNameErrorMessage.setText("**PLEASE ENTER YOUR NAME**");
        getContentPane().add(noNameErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 82, -1, -1));

        passwordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, 98, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("a number, and contain both upper case and lower case letters");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, 13));

        badPasswordErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        badPasswordErrorMessage.setText("**PLEASE ADHERE TO THE REQUIREMENTS**");
        getContentPane().add(badPasswordErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 167, -1, -1));

        noExistingDateErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        noExistingDateErrorMessage.setText("**PLEASE SELECT AN EXISTING DATE**");
        getContentPane().add(noExistingDateErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 305, -1, -1));
        getContentPane().add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 402, 103, -1));

        unappropriateAgeErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        unappropriateAgeErrorMessage.setText("**PLEASE SELECT AN APPROPRIATE AGE AS A DIGIT**");
        getContentPane().add(unappropriateAgeErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 404, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Please note that you need to be 18+  this year to be a part of this community.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 375, -1, -1));

        birthdateAndAgeDontCoicideErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        birthdateAndAgeDontCoicideErrorMessage.setText("**YOUR BIRTHDATE AND AGE DO NOT MATCH**");
        getContentPane().add(birthdateAndAgeDontCoicideErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 326, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("What's your username?");

        noOptionSelectedErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        noOptionSelectedErrorMessage.setText("**PLEASE SELECT A SINGULAR OPTION**");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(noOptionSelectedErrorMessage)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(noOptionSelectedErrorMessage)
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 450, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void yesOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesOptionActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitButtonActionPerformed
    {//GEN-HEADEREND:event_submitButtonActionPerformed
        //checking if there is input in the name field
        if(isUsernameEmpty(usernameField.getText()))
        {
            noNameErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            noNameErrorMessage.setVisible(false);
        }
        
        
        //checking if the password is valid
        if(!isPasswordValid(passwordField.getText()))
        {
            badPasswordErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            badPasswordErrorMessage.setVisible(false);
        }
        
        
        //checks to see if the date was valid
        if(!isDateReal(dayComboBox.getItemAt(dayComboBox.getSelectedIndex()), monthComboBox.getItemAt(monthComboBox.getSelectedIndex()), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())))
        {
            noExistingDateErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            noExistingDateErrorMessage.setVisible(false);
        }
        
        
        //checks to see if the age meets the requirements
        if(!isAgeWithinRange(ageField.getText()))
        {
            unappropriateAgeErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            unappropriateAgeErrorMessage.setVisible(false);
        }
        
        
        //checks to see if the age and birthdate coincide
        if(!isBirthdayAndAgeRelated(ageField.getText(), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())))
        {
            birthdateAndAgeDontCoicideErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            birthdateAndAgeDontCoicideErrorMessage.setVisible(false);
        }
        
        
        //checking if an option was chosen
        if(isNoOrTwoOptionsChosen(yesOption.isSelected(), noOption.isSelected()))
        {
            noOptionSelectedErrorMessage.setVisible(true);
        }
        else //backup for if the user needs to re enter things a second time and other components aren't valid
        {
            noOptionSelectedErrorMessage.setVisible(false);
        }
        
        
        //prints the date entered into the console
        System.out.println(" " + deriveBirthdate(dayComboBox.getItemAt(dayComboBox.getSelectedIndex()), monthComboBox.getItemAt(monthComboBox.getSelectedIndex()), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())));
        
        
        //if everything entered is correct then the user is redirected to the welcome message
        if(!isUsernameEmpty(usernameField.getText()) && isPasswordValid(passwordField.getText()) && isDateReal(dayComboBox.getItemAt(dayComboBox.getSelectedIndex()), monthComboBox.getItemAt(monthComboBox.getSelectedIndex()), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())) && isAgeWithinRange(ageField.getText()) && isBirthdayAndAgeRelated(ageField.getText(), yearComboBox.getItemAt(yearComboBox.getSelectedIndex())) && !isNoOrTwoOptionsChosen(yesOption.isSelected(), noOption.isSelected()))
        {
            new SignupComplete().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordFieldActionPerformed
    {//GEN-HEADEREND:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel badPasswordErrorMessage;
    private javax.swing.JLabel birthdateAndAgeDontCoicideErrorMessage;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JLabel noExistingDateErrorMessage;
    private javax.swing.JLabel noNameErrorMessage;
    private javax.swing.JCheckBox noOption;
    private javax.swing.JLabel noOptionSelectedErrorMessage;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel unappropriateAgeErrorMessage;
    private javax.swing.JTextField usernameField;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JCheckBox yesOption;
    // End of variables declaration//GEN-END:variables
}
